### PR TITLE
[ktor-samples-httpbin]

### PR DESCRIPTION
**Pull request by jmfayard**
Resubmitting the pull request rebased on current master 

The most interesting stuff is in [HttpbinApplication.kt](https://github.com/jmfayard/ktor/blob/sample-httpbin/ktor-samples/ktor-samples-httpbin/src/org/jetbrains/ktor/samples/httpbin/HttpbinApplication.kt)

The best way to play with the endpoints is to install https://www.getpostman.com/   and to `import` the file `httpbin.postman_collection.json`

### CODE REVIEW

**Comment by jmfayard** [comment]
Documentation is now available on http://localhost:8080/

**Comment by jmfayard** [comment]
image

**Comment by jmfayard** [comment]
Postman runner
screen shot 2017-03-18 at 21 18 20

**Comment by orangy** [comment]
I'm starting to look into it and merge process. Any further updates would need to be submitted after a merge as a separate PR.

**Comment by orangy** [comment]
Merged into branch, needs some more work here and there.

**Comment by orangy** [comment]
Finally merged into master.

**Pull request closed without merging**
